syntax = "proto3";

package SplitSpace.FinanceService;

option csharp_namespace = "SplitSpace.FinanceService.Api.FinanceService";

import "google/api/annotations.proto";
import "google/type/money.proto";
import "google/protobuf/wrappers.proto";
import "SplitSpace/FinanceService/Common.proto";

service FinanceService {
  rpc AddCategory(AddCategoryRequest) returns (AddCategoryResponse) {
    option (google.api.http) = {
      post: "/v1/category/add"
      body: "*"
    };
  }
  rpc GetCategories(GetCategoriesRequest) returns (GetCategoriesResponse) {
    option (google.api.http) = {
      post: "/v1/categories"
      body: "*"
    };
  }
  rpc AddTag(AddTagRequest) returns (AddTagResponse) {
    option (google.api.http) = {
      post: "/v1/tag/add"
      body: "*"
    };
  }
  rpc GetTags(GetTagsRequest) returns (GetTagsResponse) {
    option (google.api.http) = {
      post: "/v1/tags"
      body: "*"
    };
  }
  rpc AddAccount(AddAccountRequest) returns (AddAccountResponse) {
    option (google.api.http) = {
      post: "/v1/account/add"
      body: "*"
    };
  }
  rpc GetSpaceAccounts(GetSpaceAccountsRequest) returns (GetSpaceAccountsResponse) {
    option (google.api.http) = {
      post: "/v1/accounts/space"
      body: "*"
    };
  }
  rpc GetPersonalAccounts(GetPersonalAccountsRequest) returns (GetPersonalAccountsResponse) {
    option (google.api.http) = {
      post: "/v1/accounts/personal"
      body: "*"
    };
  }
  rpc AddExpense(AddExpenseRequest) returns (AddExpenseResponse) {
    option (google.api.http) = {
      post: "/v1/expense/add"
      body: "*"
    };
  }
  rpc GetExpenses(GetExpensesRequest) returns (GetExpensesResponse) {
    option (google.api.http) = {
      post: "/v1/expenses"
      body: "*"
    };
  }
  rpc GetDebts(GetDebtsRequest) returns (GetDebtsResponse) {
    option (google.api.http) = {
      post: "/v1/debts"
      body: "*"
    };
  }
  rpc SettleDebt(SettleDebtRequest) returns (SettleDebtResponse) {
    option (google.api.http) = {
      post: "/v1/expense/settle"
      body: "*"
    };
  }
}

message AddCategoryRequest {
  string space_id = 1;
  string user_id = 2;
  string name = 3;
  google.protobuf.StringValue parent_category_id = 4;
  optional google.type.Money limit = 5;
}

message AddCategoryResponse {
  string category_id = 1;
}

message GetCategoriesRequest {
  string space_id = 1;
  string user_id = 2;
}

message GetCategoriesResponse {
  message Category {
    string category_id = 1;
    string name = 2;
    google.protobuf.StringValue parent_category_id = 3;
    google.type.Money limit = 4;
  }
  
  repeated Category categories = 1;
}

message AddTagRequest {
  string space_id = 1;
  string user_id = 2;
  string name = 3;
}

message AddTagResponse {
  string tag_id = 1;
}

message GetTagsRequest {
  string space_id = 1;
  string user_id = 2;
}

message GetTagsResponse {
  message Tag {
    string tag_id = 1;
    string name = 2;
  }
  
  repeated Tag tags = 1;
}

message AddAccountRequest {
  string space_id = 1;
  string user_id = 2;
  string name = 3;
  google.type.Money balance = 4;
  SplitSpace.FinanceService.Common.AccountOwnerType owner_type = 5;
}

message AddAccountResponse {
  string account_id = 1;
}

message GetSpaceAccountsRequest {
  string space_id = 1;
  string user_id = 2;
}

message GetSpaceAccountsResponse {
  message Account {
    string account_id = 1;
    string name = 2;
    google.type.Money balance = 3;
    string space_id = 4;
  }
  
  repeated Account accounts = 1;
}

message GetPersonalAccountsRequest {
  string user_id = 1;
}

message GetPersonalAccountsResponse {
  message Account {
    string account_id = 1;
    string name = 2;
    google.type.Money balance = 3;
    string user_id = 4;
  }

  repeated Account accounts = 1;
}

message AddExpenseRequest {
  enum AddExpenseSplitTemplate {
    ADD_EXPENSE_SPLIT_TEMPLATE_UNSPECIFIED = 0;
    ADD_EXPENSE_SPLIT_TEMPLATE_EQUAL = 1;
  }
  message TemplateSplit {
    AddExpenseSplitTemplate template = 1;
  }
  
  message CustomSplit {
  }
  
  message Split {
    oneof type {
        TemplateSplit template_split = 1;
        CustomSplit custom_split = 2;
    }
  } 
  string space_id = 1;
  string user_id = 2;
  string category_id = 3;
  string account_id = 4;
  google.type.Money amount = 5;
  string description = 6;
  optional Split split = 7;
}

message AddExpenseResponse {
  string expense_id = 1;
}

message GetExpensesRequest {
  string space_id = 1;
  string user_id = 2;
}

message GetExpensesResponse {
  message ExpenseSplit {
    repeated ExpenseSplitItem split_items = 1;
  }
  
  message ExpenseSplitItem {
    string user_id = 1;
    google.type.Money amount_to_pay = 2;
  }
  
  message Expense {
    string expense_id = 1;
    string category_id = 2;
    string account_id = 3;
    google.type.Money amount = 4;
    string description = 5;
    optional ExpenseSplit split = 6;
  }
  
  repeated Expense expenses = 1;
}

message GetDebtsRequest {
  string space_id = 1;
  string user_id = 2;
}

message GetDebtsResponse {
  message Debt {
    string debt_id = 1;
    string space_id = 2;
    string from_user_id = 3;
    string to_user_id = 4;
    google.type.Money amount = 5;
  }
  
  repeated Debt debts = 1;
}

message SettleDebtRequest {
  string space_id = 1;
  string user_id = 2;
  string account_id = 4;
  google.type.Money amount = 5;
  string user_to = 6;
}

message SettleDebtResponse {
}
