<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Mediator.Abstractions" />
        <PackageReference Include="Dapper" />
        <PackageReference Include="Npgsql" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Scrutor" />
    </ItemGroup>
</Project>
