<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.Spaces.Domain\SplitSpace.Spaces.Domain.csproj" />
    <ProjectReference Include="..\SplitSpace.Spaces.Grpc\SplitSpace.Spaces.Grpc.csproj" />
    <ProjectReference Include="..\SplitSpace.Auth.Logic\SplitSpace.Auth.Logic.csproj" />
    <ProjectReference Include="..\SplitSpace.SharedKernel\SplitSpace.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\*.sql" />
  </ItemGroup>

</Project>
