<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SplitSpace.FinanceService.Grpc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Google.Api.CommonProtos" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\SplitSpace\**\*.proto"
              GrpcServices="Both"
              AdditionalImportDirs="Protos"
              AdditionalImportArgs="--csharp_opt=nullable=on"/>
  </ItemGroup>

  <PropertyGroup>
    <IncludeHttpRuleProtos>true</IncludeHttpRuleProtos>
  </PropertyGroup>

</Project>
