<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Mediator.SourceGenerator">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" />
    <PackageReference Include="Microsoft.AspNetCore.Grpc.Swagger" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.Auth\SplitSpace.Auth.csproj" />
    <ProjectReference Include="..\SplitSpace.Finances\SplitSpace.Finances.csproj" />
    <ProjectReference Include="..\SplitSpace.Spaces\SplitSpace.Spaces.csproj" />
  </ItemGroup>

</Project>
