<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.SpaceService.Dal\SplitSpace.SpaceService.Dal.csproj" />
    <ProjectReference Include="..\SplitSpace.SpaceService.Domain\SplitSpace.SpaceService.Domain.csproj" />
    <ProjectReference Include="..\SplitSpace.SpaceService.Producing\SplitSpace.SpaceService.Producing.csproj" />
  </ItemGroup>

</Project>
