<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\SplitSpace.FinanceService.Logic\SplitSpace.FinanceService.Logic.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Confluent.Kafka" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\" />
    </ItemGroup>
</Project>
