<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.SpaceService.Common\SplitSpace.SpaceService.Common.csproj" />
    <ProjectReference Include="..\SplitSpace.SpaceService.Domain\SplitSpace.SpaceService.Domain.csproj" />
    <ProjectReference Include="..\SplitSpace.SpaceService.Grpc\SplitSpace.SpaceService.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Migrations\001_create_tables.sql" />
    <EmbeddedResource Include="Database\Migrations\002_add_indexes.sql" />
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

</Project>
