<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Core.Api" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.ExternalFacade.Logic\SplitSpace.ExternalFacade.Logic.csproj" />
    <ProjectReference Include="..\SplitSpace.ExternalFacade.Dal\SplitSpace.ExternalFacade.Dal.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <DependentUpon>appsettings.json</DependentUpon>
    </Content>
  </ItemGroup>

</Project>
