// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitSpace.FinanceService.Dal;

#nullable disable

namespace SplitSpace.FinanceService.Dal.Migrations
{
    [DbContext(typeof(FinanceServiceDbContext))]
    [Migration("20260503081753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_type");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_account_owner_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Limit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("idx_category_parent_id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_category_space_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_debt");

                    b.HasIndex("SpaceId", "FromUserId", "ToUserId")
                        .IsUnique()
                        .HasDatabaseName("idx_debt_space_from_to");

                    b.ToTable("debt", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_expense");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("idx_expense_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_expense_category_id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("idx_expense_created_by");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_expense_space_id");

                    b.ToTable("expense", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.ExpenseSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountToPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_to_pay");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_split");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_expense_split_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_expense_split_user_id");

                    b.HasIndex("ExpenseId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_expense_split_expense_user");

                    b.ToTable("expense_split", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.ExpenseTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_tag");

                    b.HasIndex("ExpenseId")
                        .HasDatabaseName("idx_expense_tag_expense_id");

                    b.HasIndex("TagId")
                        .HasDatabaseName("idx_expense_tag_tag_id");

                    b.ToTable("expense_tag", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_account_id");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_settlement");

                    b.HasIndex("FromAccountId")
                        .HasDatabaseName("ix_settlement_from_account_id");

                    b.ToTable("settlement", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.SpaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_space_membership");

                    b.HasIndex("SpaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_space_membership_space_user");

                    b.ToTable("space_membership", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_tag_space_id");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Category", b =>
                {
                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_category_category_parent_id");
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Expense", b =>
                {
                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_account_account_id");

                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_expense_category_category_id");
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.ExpenseSplit", b =>
                {
                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_split_expense_expense_id");
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.ExpenseTag", b =>
                {
                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Expense", null)
                        .WithMany()
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_tag_expense_expense_id");

                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expense_tag_tags_tag_id");
                });

            modelBuilder.Entity("SplitSpace.FinanceService.Dal.Models.Entities.Settlement", b =>
                {
                    b.HasOne("SplitSpace.FinanceService.Dal.Models.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_settlement_account_from_account_id");
                });
#pragma warning restore 612, 618
        }
    }
}
