// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitSpace.SpaceService.Dal;

#nullable disable

namespace SplitSpace.SpaceService.Dal.Migrations
{
    [DbContext(typeof(SpaceServiceDbContext))]
    [Migration("20260428181121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SplitSpace.SpaceService.Dal.Models.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitation");

                    b.HasIndex("InvitedUserId")
                        .HasDatabaseName("idx_invitation_invited_user_id");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_invitation_space_id");

                    b.HasIndex("SpaceId", "InvitedUserId", "Status")
                        .HasDatabaseName("idx_invitation_space_user_status");

                    b.ToTable("invitation", (string)null);
                });

            modelBuilder.Entity("SplitSpace.SpaceService.Dal.Models.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_space");

                    b.ToTable("space", (string)null);
                });

            modelBuilder.Entity("SplitSpace.SpaceService.Dal.Models.Entities.SpaceMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("space_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_space_membership");

                    b.HasIndex("SpaceId")
                        .HasDatabaseName("idx_space_membership_space_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_space_membership_user_id");

                    b.HasIndex("SpaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_space_membership_space_user_unique");

                    b.ToTable("space_membership", (string)null);
                });

            modelBuilder.Entity("SplitSpace.SpaceService.Dal.Models.Entities.Invitation", b =>
                {
                    b.HasOne("SplitSpace.SpaceService.Dal.Models.Entities.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_space_space_id");
                });

            modelBuilder.Entity("SplitSpace.SpaceService.Dal.Models.Entities.SpaceMembership", b =>
                {
                    b.HasOne("SplitSpace.SpaceService.Dal.Models.Entities.Space", null)
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_space_membership_space_space_id");
                });
#pragma warning restore 612, 618
        }
    }
}
