<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SplitSpace.AuthService.Dal\SplitSpace.AuthService.Dal.csproj" />
    <ProjectReference Include="..\SplitSpace.AuthService.Common\SplitSpace.AuthService.Common.csproj" />
    <ProjectReference Include="..\SplitSpace.AuthService.Grpc\SplitSpace.AuthService.Grpc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

</Project>
