<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageReference Include="Npgsql" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SplitSpace.Auth.Domain\SplitSpace.Auth.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Database\Migrations\*.sql" />
    </ItemGroup>

</Project>
