syntax = "proto3";

package SplitSpace.Spaces;

option csharp_namespace = "SplitSpace.Spaces.Api";

import "google/api/annotations.proto";

service InvitationService {
  rpc InviteUser(InviteUserRequest) returns (InviteUserResponse) {
    option (google.api.http) = {
      post: "/v1/invite/create"
      body: "*"
    };
  }
  rpc AcceptInvitation(AcceptInvitationRequest) returns (AcceptInvitationResponse) {
    option (google.api.http) = {
      post: "/v1/invite/accept"
      body: "*"
    };
  }
  rpc RejectInvitation(RejectInvitationRequest) returns (RejectInvitationResponse) {
    option (google.api.http) = {
      post: "/v1/invite/reject"
      body: "*"
    };
  }
}

message InviteUserRequest {
  string invited_user_email = 1;
  string invited_by_user_id = 2;
  string space_id = 3;
}

message InviteUserResponse {
  string invitation_id = 1;
}

message AcceptInvitationRequest {
  string invitation_id = 1;
  string user_id = 2;
}

message AcceptInvitationResponse {
}

message RejectInvitationRequest {
  string invitation_id = 1;
  string user_id = 2;
}

message RejectInvitationResponse {
}
