<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <!-- gRPC packages -->
    <PackageVersion Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="2.76.0" />
    <PackageVersion Include="Grpc.Core.Api" Version="2.76.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.76.0" />
    <PackageVersion Include="Grpc.Net.Common" Version="2.76.0" />
    <PackageVersion Include="Google.Protobuf" Version="3.31.1" />
    <PackageVersion Include="Grpc.Tools" Version="2.76.0" />
    
    <!-- Dal -->
    <PackageVersion Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.6" />
    <PackageVersion Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.10.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.4" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />

    <!-- Logic -->
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.0.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
    
    <!-- Main -->

    <PackageVersion Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    
  </ItemGroup>
  
  <ItemGroup>
    <!-- Test -->
    <PackageVersion Include="coverlet.collector" Version="6.0.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.1" />
  </ItemGroup>
</Project>
