syntax = "proto3";

package SplitSpace.Finances;

option csharp_namespace = "SplitSpace.Finances.Api.SearchService";

import "google/api/annotations.proto";
import "google/type/money.proto";
import "google/type/date.proto";
import "google/protobuf/wrappers.proto";

service SearchService {
  rpc GetReport(GetReportRequest) returns (GetReportResponse) {
    option (google.api.http) = {
      post: "/v1/report"
      body: "*"
    };
  }
}

message GetReportRequest {
  string space_id = 1;
  string user_id = 2;
  
  google.type.Date from = 3;
  google.type.Date to = 4;
  google.protobuf.StringValue timezone = 5; // IANA format
}

message GetReportResponse {
  message ReportItem {
    string category_id = 1;
    google.type.Money amount = 2;
  }
  
  repeated ReportItem items = 1;
}
