<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <!-- gRPC packages -->
    <PackageVersion Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageVersion Include="Google.Protobuf" Version="3.33.0" />
    <PackageVersion Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageVersion Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0" />
    <PackageVersion Include="Grpc.Core.Api" Version="2.80.0" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.80.0" />
    <PackageVersion Include="Grpc.Net.Common" Version="2.80.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.80.0" />

    <!-- ASP.NET Core / gRPC JSON + Swagger -->
    <PackageVersion Include="Microsoft.AspNetCore.Grpc.JsonTranscoding" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Grpc.Swagger" Version="0.10.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />

    <!-- Microsoft.Extensions packages -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />

    <!-- Security & Identity packages -->
    <PackageVersion Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageVersion Include="Microsoft.IdentityModel.Tokens" Version="8.21.0" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.2.3" />

    <!-- Test packages -->
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />

    <!-- Mediator -->
    <PackageVersion Include="Mediator.SourceGenerator" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Mediator.Abstractions" Version="3.0.2" />

    <!-- Data access -->
    <PackageVersion Include="Dapper" Version="2.1.79" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
</Project>